name: dbt_production_daily

on: workflow_dispatch
    
jobs:
  dbt_production_daily:
    name: dbt_production_daily
    runs-on: ubuntu-latest

    env:
      DBT_PROFILES_DIR: ./
      DEPLOY_DBT_COURSE_SNOWFLAKE_ACCOUNT_ID: ${{ secrets.DEPLOY_DBT_COURSE_SNOWFLAKE_ACCOUNT_ID }}
      DEPLOY_DBT_COURSE_SNOWFLAKE_USERNAME: ${{ secrets.DEPLOY_DBT_COURSE_SNOWFLAKE_USERNAME }}
      DEPLOY_DBT_COURSE_SNOWFLAKE_PASSWORD: ${{ secrets.DEPLOY_DBT_COURSE_SNOWFLAKE_PASSWORD }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-snowflake==1.6.0
        dbt deps --target prod

    - name: Run all models
      run: |
        dbt run --target prod
